language: node_js

node_js:
    - 10
    - 8

cache:
    yarn: true

branches:
    only:
        - master

before_install:
    - npm i -g yarn

install:
    - yarn install

script:
    - node ./test.js
    - yarn lint
