environment:
  matrix:
    - node_version: "10"
    - node_version: "8"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:node_version
  - npm install

build_script:
  - npm run build
  - npm run example:build

test_script:
  - node ./test.js
  - yarn lint

cache:
  - node_modules
