environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "13"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

cache:
  - node_modules

# Don't actually build.
build: off
