environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node ./test.js
  - npm run lint

cache:
  - node_modules
